---
- name: Create Docker Image 
  hosts: dev
  become: true
  tasks:
  - name: Build an image 
    community.docker.docker_image:
      name: ansible-docker-image:ad1
      build:
        path: /tmp/classwebsite2/
        args:
          listen_port: 80
      source: build
  - name: Create Container1
    community.docker.docker_container:
      name: adc1
      image: ansible-docker-image:ad1
      state: started
      ports:
        - "8080:80"
