name: Docker-Gha CI/CD

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Path to the Dockerfile context
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/classwebsite2-gha-webapp:v08sep25
          
